import{i,S as c}from"./assets/vendor-7659544d.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();const l="35544467-972bad3ac294320c3ee48db53",d="https://pixabay.com/api/";async function u(n){const s=`${d}?key=${l}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`;try{const t=await fetch(s);if(!t.ok)throw new Error("Failed to fetch images");return(await t.json()).hits}catch(t){throw console.error("Error fetching images:",t.message),t}}function m(){i.show({title:"Loading",message:"Fetching images from Pixabay...",theme:"dark",progressBarColor:"#17a2b8",position:"bottomRight"})}function f(){i.hide({},document.querySelector(".iziToast"))}function h(n){const s=document.querySelector(".gallery");if(s.innerHTML="",n.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});return}const t=document.createDocumentFragment();n.forEach(r=>{const e=document.createElement("div");e.classList.add("card"),e.innerHTML=`
            <img src="${r.webformatURL}" alt="${r.tags}" data-large="${r.largeImageURL}">
            <div class="info">
                <span>${r.likes} Likes</span>
                <span>${r.views} Views</span>
                <span>${r.comments} Comments</span>
                <span>${r.downloads} Downloads</span>
            </div>
        `,t.appendChild(e)}),s.appendChild(t)}const p=document.querySelector("#search-form");p.addEventListener("submit",async n=>{n.preventDefault();const t=document.querySelector("#search-input").value.trim();if(!t){iziToast.warning({title:"Warning",message:"Please enter a search query",position:"topCenter"});return}m();try{const r=await u(t);h(r),new c(".gallery img").refresh()}catch(r){console.error("Error searching for images:",r.message)}finally{f()}});
//# sourceMappingURL=commonHelpers.js.map
